project:
  type: book

book:
  title: "Introduction to Model-based Statistics"
  subtitle: "Frequentist and Bayesian Reasoning with Simulation"
  author: "Dr. Cheng-Han Yu"
  date: today
  site-url: https://chenghanyu-fbi.netlify.app/
  repo-url: https://github.com/chenghanyustats/fbi
  chapters:
    - index.qmd
    - 00-recommendation.qmd
    - part1.qmd
    # - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



